require('plugins')
require('keys')
require('look')
require('misc')

require('plugins.nerdcommenter')
require('plugins.gitgutter')
require('plugins.lexima')
require('plugins.lightline')
require('plugins.deoplete')
require('plugins.languageclient')
require('plugins.nvim-treesitter')
