# History config
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=100000

# Vi key bindings
bindkey -v

# Configuring keys
typeset -g -A key

key[Home]="$terminfo[khome]"
key[End]="$terminfo[kend]"
key[Insert]="$terminfo[kich1]"
key[Backspace]="$terminfo[kbs]"
key[Delete]="$terminfo[kdch1]"
key[Up]="$terminfo[kcuu1]"
key[Down]="$terminfo[kcud1]"
key[Left]="$terminfo[kcub1]"
key[Right]="$terminfo[kcuf1]"
key[PageUp]="$terminfo[kpp]"
key[PageDown]="$terminfo[knp]"

[[ -n "$key[Home]"      ]] && bindkey -- "$key[Home]"      beginning-of-line
[[ -n "$key[End]"       ]] && bindkey -- "$key[End]"       end-of-line
[[ -n "$key[Insert]"    ]] && bindkey -- "$key[Insert]"    overwrite-mode
[[ -n "$key[Backspace]" ]] && bindkey -- "$key[Backspace]" backward-delete-char
[[ -n "$key[Delete]"    ]] && bindkey -- "$key[Delete]"    delete-char
[[ -n "$key[Up]"        ]] && bindkey -- "$key[Up]"        history-substring-search-up
[[ -n "$key[Down]"      ]] && bindkey -- "$key[Down]"        history-substring-search-down
[[ -n "$key[Left]"      ]] && bindkey -- "$key[Left]"      backward-char
[[ -n "$key[Right]"     ]] && bindkey -- "$key[Right]"     forward-char

if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
    function zle-line-init () {
        echoti smkx
    }
    function zle-line-finish () {
        echoti rmkx
    }
    zle -N zle-line-init
    zle -N zle-line-finish
fi

# ls color
alias ls="ls --color"

# The most awesome editor in the unverse (until I find another)
export EDITOR=nvim
alias vim=nvim
alias vi=nvim

# Path
export GOPATH=$HOME/.go
export PREFIX=$HOME/.yarn_packages
export RUST_SRC_PATH=$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
path=($PREFIX/bin $HOME/.local/bin $HOME/.cargo/bin $GOPATH/bin $path)

# Ripgrep instead of grep
alias grep=rg

# IRC amazon instance
alias irc="ssh irc_aws -t 'tmux attach-session -t irc_session'"

# Check writing on disk
check-sync() {
    watch grep -e Dirty: -e Writeback: /proc/meminfo
}

# Sync git forks
sync-fork() {
    git fetch upstream
    git checkout master
    git merge upstream/master
    git push
}
