# History config
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=100000

# ls color
alias ls="ls --color"

# The most awesome editor in the unverse (until I find another)
export EDITOR=nvim
alias vim=nvim
alias vi=nvim

# Path
export GOPATH=$HOME/.go
export PREFIX=$HOME/.yarn_packages
export RUST_SRC_PATH=$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
path=($PREFIX/bin $HOME/.local/bin $HOME/.cargo/bin $GOPATH/bin $path)

# Ripgrep instead of grep
alias grep=rg

# IRC amazon instance
alias irc="ssh irc_aws -t 'tmux attach-session -t irc_session'"

# Check writing on disk
check-sync() {
    watch grep -e Dirty: -e Writeback: /proc/meminfo
}

# Sync git forks
sync-fork() {
    git fetch upstream
    git checkout master
    git merge upstream/master
    git push
}
